apiVersion: v1
kind: Service
metadata:
  name: tenantservice
  labels:
    app: tenantservice
spec:
  type: NodePort
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: tenantservice