version: "3.7"

services:
  web:
    build:
      './web'
    expose:
      - 3000
    environment:
      - AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY

  tenantservice:
    build:
      './tenantservice'
    expose:
      - 3002
    environment:
      - AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY

  transcribe:
    build:
      './transcribe'
    expose:
      - 3001
    environment:
      - AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY

  nginx:
    build:
      './nginx'
    ports:
      - "80:80"
    depends_on:
      - web
      - tenantservice
      - transcribe