---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: transcribe
spec:
  replicas: 1 #This number has been chosen due to the increased cost that comes with more replicas. We are aware of this functionality
  selector:
    matchLabels:
      app: transcribe
  template:
    metadata:
      labels:
        app: transcribe
    spec:
      containers:
        - name: transcribe
          image: leonsick/transcribe_by_bzs:transcribe
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: AWS_ACCESS_KEY_ID
              value: 'AWS KEY'
            - name: AWS_SECRET_ACCESS_KEY
              value: 'AWS KEY'
