apiVersion: v1
kind: Service
metadata:
  name: transcribe
  labels:
    app: transcribe
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: transcribe